# Generated by Django 4.1.6 on 2023-02-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name="User's Picture")),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'LOCAL'), (2, 'FOREIGN')], null=True, verbose_name='User Type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
