# Generated by Django 4.1.6 on 2023-02-14 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.DateField(null=True, verbose_name='Birthday')),
                ('picture', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d', verbose_name="User's Picture")),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('social_media', models.CharField(max_length=50, null=True, verbose_name='Social Media Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User's Account")),
            ],
        ),
    ]
