import { getAllItems } from '@/services'
import Head from 'next/head'
import Image from 'next/image'
import { GetStaticProps } from 'next'
import { InferGetStaticPropsType } from 'next'
import Hero from '@/components/Hero'

export default function Home({items}: InferGetStaticPropsType<typeof getStaticProps>) {
  
  return (
    <>
      <Head>
        <title>Beyond Borders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  
  const items = (await getAllItems())

  return {
    props: {
      items,
    },
  }
}
